image: registry.gitlab.com/specktrum/vimwiki_extensions:latest

stages:
  - format
  - lint
  - typing
  - test
  - update

format:
  stage: format
  script:
    - ./run.sh format

lint:
  stage: lint
  script:
    - ./run.sh lint

typing:
  stage: typing
  script:
    - ./run.sh typing

test:
  stage: test
  script:
    - ./run.sh test
